### ISSUE TITLE
Supporting import

### ISSUE THREAD

**Issue by mike-stewart-dev** [sindresorhus/filename-reserved-regex#3]
Hi,

I'm getting the following error when importing this package:

> Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /redacted/path/node_modules/filename-reserved-regex/index.js
> require() of ES modules is not supported.
> require() of /redacted/path/node_modules/filename-reserved-regex/index.js from /redacted/path/build/server.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
> Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /redacted/path/node_modules/filename-reserved-regex/package.json.
> 
>     at new NodeError (node:internal/errors:363:5)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:13)
>     at Module.load (node:internal/modules/cjs/loader:975:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:816:12)
>     at Module.require (node:internal/modules/cjs/loader:999:19)
>     at require (node:internal/modules/cjs/helpers:93:18)
>     at Object.<anonymous> (/redacted/path/build/server.js:22:46)
>     at Module._compile (node:internal/modules/cjs/loader:1095:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
>     at Module.load (node:internal/modules/cjs/loader:975:32)
> ERROR: "dev:server" exited with 1.

It is possible to implement one of the suggestions in the error? 

Thanks

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
